---
title: "Global Use of OJS, 2019"
subtitle: "Active journals (at least 5 records in 2019) using OJS"
#author: "Saurabh Khanna"
date: "Updated: `r Sys.Date()`"
output:
  html_document:
    toc: false
---

---

Total count: 14,458 active journals<sup>1</sup>

--- 

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.retina = 4)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, countrycode, sf, state, htmltools, htmlwidgets, urltools, lubridate, janitor, plotly)

# Data
df <- read_csv(here::here("data", "beacon-2019-min5.csv"))

shapefile <- read_sf(here::here("data/TM_WORLD_BORDERS_SIMPL-0.3.shp"))
tld <- read_csv(here::here("data", "tld-country.csv"))
tld_from_ip <- read_csv(here::here("data", "tld_from_ip.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")
```


```{r}
# correcting some oai urls
df <- df %>% mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))
```


```{r}
df <- 
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  left_join(tld_from_ip, by = "domain") %>%
  mutate(
    tld = if_else(!is.na(tld_from_ip), tld_from_ip, tld)
  ) %>%
  left_join(tld, by = "tld")
```


```{r}
# Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = if_else(is.na(country), country_clean, country),
    ojs_v2 = str_detect(version, "^ojs2/2"),
    ojs_v3 = str_detect(version, "^ojs2/3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country),
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country)
  )

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to continent
names(df)[length(names(df))] <- "continent"

rm(tld, tld_from_ip)

# merging morocco and western sahara
shapefile <-
  shapefile %>% 
  janitor::clean_names() %>% 
  mutate(
    name = if_else(name == "Western Sahara", "Morocco", name)
  ) %>%
  arrange(name) %>% 
  group_by(name) %>% 
  summarize(
    geometry = st_union(geometry),
    lat = first(lat),
    lon = first(lon),
    region = first(region)
  ) %>% 
  st_cast("MULTIPOLYGON")
```


```{r}
# creating grouped dfs
df_world <-
  df %>%
  drop_na(country) %>%   
  group_by(country, continent) %>% 
  summarize(
    ojs_v2 = sum(ojs_v2, na.rm = T),
    ojs_v3 = sum(ojs_v3, na.rm = T)
  ) %>% 
  ungroup() %>% 
  transmute(
    country,
    continent,
    ojs_v2,
    ojs_v3,
    total = ojs_v2 + ojs_v3
  ) %>% 
  mutate(
    total = replace_na(total, 0),
    ojs_v2 = replace_na(ojs_v2, 0),
    ojs_v3 = replace_na(ojs_v3, 0)
  )
```


```{r, out.width="100%"}
fill_threshold <- 500

plot <-
  shapefile %>% 
  janitor::clean_names() %>%
  rename(country = name) %>%
  mutate(
    country = if_else(country == "Libyan Arab Jamahiriya", "Libya", country),
    country = if_else(country == "United Republic of Tanzania", "Tanzania", country),
    country = if_else(country == "Cote d'Ivoire", "Côte d'Ivoire", country),
    country = if_else(country == "Congo", "Republic of the Congo", country),
    country = if_else(country == "Viet Nam", "Vietnam", country),
    country = if_else(str_detect(country, "Iran"), "Iran", country),
    country = if_else(str_detect(country, "Korea, Republic of"), "South Korea", country),
    country = if_else(str_detect(country, "Korea, Democratic People's Republic of"), "North Korea", country),
    country = if_else(str_detect(country, "Surinam"), "Surinam", country)
  ) %>%
  left_join(df_world, by = "country") %>% 
  filter(country != "Antarctica") %>% 
  mutate(
    total = replace_na(total, 0),
    subtext = str_c(total, " journals"),
    hover_text = str_c(country, subtext, sep = "\n"),
    total = pmin(total, fill_threshold)
  ) %>%
  ggplot() +
  geom_sf(aes(fill = total, text = hover_text), size = 0.3, show.legend = FALSE) +
  scale_fill_gradientn(
    colors = RColorBrewer::brewer.pal(n = 9, name = "PuRd")
  ) +
  theme_minimal()

ggplotly(plot, tooltip = "hover_text") %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```


```{r}
df_world %>% 
  filter(total > 0) %>%
  arrange(-total) %>% 
  select(Country = country, `OJS Total Active` = total) %>%
  DT::datatable()
```

<br/>

---

<small><b>1</b> The `hover` in the interactive map works along country borders instead of within country regions. When two countries share a border, the `hover` shows the country with more active journals.</small>
