---
title: "OJS Research Dashboard - Indonesia"
author: "Saurabh Khanna"
date: "Updated: `r Sys.Date()`"
output: 
  html_document:
    toc: false
    toc_depth: 4
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.retina = 4)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, countrycode, state, htmltools, htmlwidgets, urltools, janitor)

# Data
df <- read_csv(here::here("data/beacon-latest/beacon-2021-02-02.csv"))
tld <- read_csv(here::here("data", "tld-country.csv"))
tld_from_ip <- read_csv(here::here("data", "tld_from_ip.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")
```


```{r}
# correcting some oai urls
df <- df %>% mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))
```


```{r}
df <- 
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  left_join(tld_from_ip, by = "domain") %>%
  mutate(
    tld = if_else(!is.na(tld_from_ip), tld_from_ip, tld)
  ) %>%
  left_join(tld, by = "tld")
```


```{r}
# Cleaning countries + Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = if_else(is.na(country), country_clean, country),
    ojs_v2 = str_detect(version, "^ojs2/2"),
    ojs_v3 = str_detect(version, "^ojs2/3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country),
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country)
  )

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to `continent`
names(df)[length(names(df))] <- "continent"

rm(tld, tld_from_ip)
```


<br/><br/>

### OJS Version 2 installation URLs in Indonesia by number of active and present journals

<br/>

```{r}
df_ind_present <-
  df %>%
  filter(country == "Indonesia" & ojs_v2) %>% 
  count(domain, name = "ojs_v2_present")

df_ind_active <-
  df %>%
  filter(country == "Indonesia" & ojs_v2 & record_count_2019 >= 5) %>% 
  count(domain, name = "ojs_v2_active")

df_ind_present %>%
  left_join(df_ind_active, by = "domain") %>% 
  mutate(
    ojs_v2_active = replace_na(ojs_v2_active, 0),
    domain = str_c('<a href="http://', domain, '" target="_blank">', domain, '</a>')
    ) %>%
  arrange(-ojs_v2_active) %>%
  select(`V2 installation URL` = domain, `V2 active` = ojs_v2_active, `V2 present` = ojs_v2_present) %>% 
  DT::datatable(escape = F, options = list(pageLength = 25))
```

