---
title: "Global Use of OJS"
subtitle: "Active journals (at least 10 records since the start of 2019) using OJS"
date: "Updated: `r Sys.Date()`"
output:
  html_document:
    toc: false
---

---


```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.retina = 4)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, countrycode, sf, state, htmltools, htmlwidgets, urltools, janitor, DT, RColorBrewer, plotly, readxl)
tld <- read_csv(here::here("data/tld-country.csv"))
tld_from_ip <- read_csv(here::here("data/tld_from_ip.csv"))
shapefile <- read_sf(here::here("data/TM_WORLD_BORDERS_SIMPL-0.3.shp"))
```


```{r}
# Data
df <- read_csv(here::here("data/jonas/beacon-report-2019.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")

# correcting some oai urls
df <- 
  df %>% 
  mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))

# getting domain and tld
df <- 
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  left_join(tld_from_ip, by = "domain") %>%
  mutate(
    tld = if_else(!is.na(tld_from_ip), tld_from_ip, tld)
  ) %>%
  left_join(tld, by = "tld")

# Cleaning countries + Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = if_else(is.na(country), country_clean, country),
    ojs_v2 = str_detect(version, "^ojs2/2"),
    ojs_v3 = str_detect(version, "^ojs2/3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country),
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England|British"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country)
  ) %>% 
  select(-country_clean)

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to `continent`
names(df)[length(names(df))] <- "continent"

df2019 <- df %>% filter(total_record_count > 0) %>% select(record_count_2019, total_record_count, oai_url, version, repository_name, issn, country, set_spec, earliest_datestamp, domain)
```



```{r}
# Data
df <- read_csv(here::here("data/jonas/beacon-report-2020.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")

# correcting some oai urls
df <- 
  df %>% 
  mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))

# getting domain and tld
df <- 
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  left_join(tld_from_ip, by = "domain") %>%
  mutate(
    tld = if_else(!is.na(tld_from_ip), tld_from_ip, tld)
  ) %>%
  left_join(tld, by = "tld")

# Cleaning countries + Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = if_else(is.na(country), country_clean, country),
    ojs_v2 = str_detect(version, "^ojs2/2"),
    ojs_v3 = str_detect(version, "^ojs2/3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country),
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England|British"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country)
  ) %>% 
  select(-country_clean)

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to `continent`
names(df)[length(names(df))] <- "continent"

df2020 <- df %>% filter(total_record_count > 0) %>% select(record_count_2020, total_record_count, oai_url, version, repository_name, issn, country, set_spec, earliest_datestamp, domain)
```



```{r}
# Data
df <- read_csv(here::here("data/jonas/beacon-report-2021.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")

# correcting some oai urls
df <- 
  df %>% 
  mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))

# getting domain and tld
df <- 
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  left_join(tld_from_ip, by = "domain") %>%
  mutate(
    tld = if_else(!is.na(tld_from_ip), tld_from_ip, tld)
  ) %>%
  left_join(tld, by = "tld")

# Cleaning countries + Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = if_else(is.na(country), country_clean, country),
    ojs_v2 = str_detect(version, "^ojs2/2"),
    ojs_v3 = str_detect(version, "^ojs2/3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country),
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England|British"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country)
  ) %>% 
  select(-country_clean)

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to `continent`
names(df)[length(names(df))] <- "continent"

df2021 <- df %>% filter(total_record_count > 0) %>% select(record_count_2021, total_record_count, oai_url, version, repository_name, issn, country, set_spec, earliest_datestamp, domain)
```



```{r}
df <-
  df2019 %>%
  full_join(df2020, by = c("oai_url", "version", "repository_name", "issn", "country", "set_spec")) %>% 
  full_join(df2021, by = c("oai_url", "version", "repository_name", "issn", "country", "set_spec")) %>%
  arrange(oai_url, repository_name, set_spec, desc(earliest_datestamp)) %>% 
  distinct(oai_url, repository_name, set_spec, .keep_all = T) %>%
  mutate(
    record_count_2019_or_later = record_count_2019 + record_count_2020 + record_count_2021,
    active = (record_count_2019_or_later >= 10),
    set_spec = set_spec %>% str_trim() %>% str_to_upper(),
    repository_name = repository_name %>% str_trim() %>% str_to_upper(),
  )
```


```{r, eval=F}
# detective work for kevin
df_doaj <- 
  read_excel(here::here("data/kevin/kevin_doaj.xlsx")) %>% clean_names() %>% 
  remove_empty()

df_doaj <-
  bind_cols(
    df_doaj,
    df_doaj %>% pull(journal_url) %>% domain() %>% tld_extract()
  ) %>%
  mutate(
    platform = platform_host_or_aggregator %>% str_trim() %>% str_to_upper(),
    journal_title = journal_title %>% str_trim() %>% str_to_upper(),
    publisher = publisher %>% str_trim() %>% str_to_upper(),
    country = country_of_publisher %>% str_trim(),
    issn = journal_eissn_online_version %>% str_trim(),
    ojs = str_detect(platform, "OJS|NEPJOL|AJOL|SEER|OPEN JOURNAL SYSTEM")
  )

# question 1
df_doaj %>% 
  filter(ojs) %>% 
  anti_join(df, by = "issn") %>% 
  anti_join(df, by = "domain") %>% 
  anti_join(df, by = c("journal_title" = "set_spec")) %>% 
  anti_join(df, by = c("publisher" = "repository_name")) %>% 
  arrange(country, publisher, journal_title) %>% 
  relocate(country, publisher, journal_title) %>% 
  count(country) %>% arrange(-n)

df_doaj %>% 
  filter(ojs) %>% 
  anti_join(df, by = "issn") %>% 
  anti_join(df, by = "domain") %>% 
  anti_join(df, by = c("journal_title" = "set_spec")) %>% 
  anti_join(df, by = c("publisher" = "repository_name")) %>% 
  arrange(country, publisher, journal_title) %>% 
  relocate(country, publisher, journal_title) %>% 
  summarise_all(~ mean(is.na(.)))

# question 2
# df_doaj %>%
#   filter((!ojs | is.na(ojs)) & !is.na(issn)) %>%
#   inner_join(df, by = "issn")
# 
# df_doaj %>%
#   filter((!ojs | is.na(ojs)) & !is.na(domain)) %>%
#   inner_join(df, by = "domain")


# checks
df_doaj %>% 
  filter(ojs) %>% 
  anti_join(df, by = "issn") %>% 
  anti_join(df, by = "domain") %>% 
  anti_join(df, by = c("journal_title" = "set_spec")) %>% 
  anti_join(df, by = c("publisher" = "repository_name")) %>% 
  arrange(country, publisher, journal_title) %>% 
  relocate(country, publisher, journal_title) %>% 
  filter(str_detect(country, "Finland")) %>% 
  distinct(domain)

df %>% 
  filter(str_detect(domain, "wittgenstein"), country == "Brazil") %>% 
  distinct(domain.x)

df_doaj %>% 
  filter(ojs) %>% 
  anti_join(df, by = "issn") %>% 
  anti_join(df, by = "domain") %>% 
  anti_join(df, by = c("journal_title" = "set_spec")) %>% 
  anti_join(df, by = c("publisher" = "repository_name")) %>% 
  arrange(country, publisher, journal_title) %>% 
  relocate(country, publisher, journal_title) %>%
  distinct(domain)
```


























```{r}
# creating grouped dfs
df_world <-
  df %>% 
  tabyl(country, active) %>% 
  as_tibble() %>% 
  drop_na(country) %>% 
  rename(inactive = `FALSE`, active = `TRUE`) %>% 
  mutate(
    total = inactive + active,
    perc_active = ((active/total) * 100) %>% round(digits = 2)
  ) %>% 
  arrange(-total)

# df_world %>% 
#   summarise(
#     active = sum(active, na.rm = TRUE),
#     inactive = sum(inactive, na.rm = TRUE),
#     total = sum(total, na.rm = TRUE)
#   ) %>% 
#   mutate(
#     perc_active = ((active/total) * 100) %>% round(digits = 2)
#   )

active <- df_world %>% summarise(active = sum(active, na.rm = TRUE)) %>% pull(active)
```

Total count: `r toString(active)` active journals<sup>1</sup>

---

```{r, out.width="100%"}
plot <-
  shapefile %>% 
  clean_names() %>%
  rename(country = name) %>%
  mutate(
    country = if_else(country == "Libyan Arab Jamahiriya", "Libya", country),
    country = if_else(country == "United Republic of Tanzania", "Tanzania", country),
    country = if_else(country == "Cote d'Ivoire", "Côte d'Ivoire", country),
    country = if_else(country == "Congo", "Republic of the Congo", country),
    country = if_else(country == "Viet Nam", "Vietnam", country),
    country = if_else(str_detect(country, "Iran"), "Iran", country),
    country = if_else(str_detect(country, "Korea, Republic of"), "South Korea", country),
    country = if_else(str_detect(country, "Korea, Democratic People's Republic of"), "North Korea", country),
    country = if_else(str_detect(country, "Surinam"), "Surinam", country)
  ) %>%
  left_join(df_world, by = "country") %>% 
  filter(country != "Antarctica") %>% 
  mutate(
    active = replace_na(active, 0),
    subtext = str_c(active, " active journals"),
    hover_text = str_c(country, subtext, sep = "\n"),
    active = pmin(active, 500)
  ) %>%
  ggplot() +
  geom_sf(aes(fill = active, text = hover_text), size = 0.3, show.legend = FALSE) +
  scale_fill_gradientn(
    breaks = seq(0, 500, 250),
    colors = RColorBrewer::brewer.pal(n = 9, name = "PuRd")
  ) +
  theme_minimal()

ggplotly(plot, tooltip = "hover_text") %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

```{r}
df_world %>% 
  arrange(-active) %>%
  relocate(country, active, inactive) %>% 
  DT::datatable(options = list(pageLength = 25))
```

<br/>

---

<small><b>1</b> The `hover` in the interactive map works along country borders instead of within country regions. When two countries share a border, the `hover` shows the country with more active journals.</small>
