---
title: "Morocco - Number of journals"
#author: "Saurabh and Oumnia"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, sf, plotly)

# Data
df <- read_csv(here::here("data/oumnia_map.csv"))

df <-
  df %>% 
  transmute(
    n_journals,
    city,
    latitude = parse_number(lat),
    longitude = -parse_number(lon),
    name = "Morocco"
  )

shapefile <- read_sf(here::here("data/TM_WORLD_BORDERS_SIMPL-0.3.shp"))

shapefile <-
  shapefile %>% 
  janitor::clean_names() %>% 
  mutate(
    name = if_else(name == "Western Sahara", "Morocco", name)
  ) %>%
  arrange(name) %>% 
  group_by(name) %>% 
  summarize(
    geometry = st_union(geometry),
    lat = first(lat),
    lon = first(lon),
    region = first(region)
  ) %>% 
  st_cast("MULTIPOLYGON")

df <-
  shapefile %>% 
  filter(name == "Morocco") %>% 
  inner_join(df, by = "name")
```


Below is the map of number of journals in Morocco.

```{r}
plot <-
  df %>% 
  ggplot() +
  geom_sf() +
  geom_point(aes(x = longitude, y = latitude, size = n_journals, text = city), alpha = 0.5, color = "blue") +
  scale_size(range = c(1, 20)) +
  theme_minimal()


ggplotly(plot, tooltip = c("city", "n_journals"))
```

