---
title: "OJS Growth"
date: "Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
---

---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.retina = 4)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, countrycode, sf, state, htmltools, htmlwidgets, urltools, janitor, DT, RColorBrewer, plotly, readxl, ggforce)
tld <- read_csv(here::here("data/tld-country.csv"))
tld_from_ip <- read_csv(here::here("data/tld_from_ip.csv"))
```

# Global

```{r}
# Data (Aug 5, 2021)
df <- read_csv(here::here("data/beacon-public.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")

# correcting some oai urls
df <- 
  df %>% 
  mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))


# getting domain and tld
df <-  
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  mutate(country_consolidated = str_to_lower(country_consolidated) %>% str_trim()) %>% 
  left_join(tld, by = c("country_consolidated" = "tld"))

# Cleaning countries + Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = country_clean,
    ojs_v2 = str_detect(version, "^2"),
    ojs_v3 = str_detect(version, "^3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country),
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England|British"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country)
  ) %>% 
  select(-country_clean)

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to `continent`
names(df)[length(names(df))] <- "continent"

df_2020 <-
  df %>% 
  filter(total_record_count > 0) %>%
  filter(application == "ojs") %>%
  mutate(active = (record_count_2020 >= 5)) %>% filter(active) %>% 
  distinct(oai_url, repository_name, set_spec, .keep_all = T)

df_2021 <-
  df %>% 
  filter(total_record_count > 0) %>%
  filter(application == "ojs") %>%
  mutate(active = (record_count_2021 >= 5)) %>% filter(active) %>% 
  distinct(oai_url, repository_name, set_spec, .keep_all = T)

df_2020 %>% 
  count(country) %>%
  drop_na(country) %>% 
  arrange(-n)
```


<br/>

## Active journals (5 or more records published per year)

```{r, fig.retina=4, out.width="100%"}
df %>% 
  select(context_name, record_count_2010:record_count_2020) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  filter(value >= 5) %>% 
  count(name) %>%
  mutate(name = as.integer(name)) %>% 
  ggplot(aes(name, n)) +
  geom_line() +
  geom_point(size = 2) +
  theme_classic() +
  scale_x_continuous(breaks = seq(2010, 2020, 1)) +
  scale_y_continuous(breaks = seq(0, 25000, 5000)) +
  theme(
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 10),
    axis.ticks = element_blank(),
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(
    x = "Year",
    y = "Journals",
  )

ggsave(here::here("ojs_growth_2010-2020.png"))
```

```{r}
# Percentage growth every year

# df %>%
#   drop_na(country) %>% 
#   select(context_name, record_count_1980:record_count_2020) %>% 
#   pivot_longer(cols = starts_with("record_count")) %>% 
#   mutate(
#     name = parse_number(name)
#   ) %>% 
#   filter(value >= 5) %>% 
#   count(name) %>% 
#   mutate(percent_growth_since_previous_year = round((n/lag(n) - 1) * 100, 2)) %>% 
#   rename(year = name, active_journals = n) %>% 
#   write_csv(here::here("ojs_growth_rate_by_year.csv"))

df %>%
  # drop_na(country) %>% 
  select(context_name, record_count_2010:record_count_2020) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  filter(value >= 5) %>% 
  count(name) %>% 
  mutate(percent_growth_since_previous_year = round((n/lag(n) - 1) * 100, 2)) %>% 
  rename(year = name, active_journals = n) %>% 
  # arrange(-year) %>% mutate(percent_growth_since_previous_year = str_c(as.character(percent_growth_since_previous_year), "%"))
  ggplot(aes(year, percent_growth_since_previous_year)) +
  geom_col(alpha = 0.8) +
  scale_x_continuous(breaks = seq(1980, 2020, 5)) +
  scale_y_continuous(breaks = seq(0, 35, 5)) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Year",
    y = "OJS Growth Rate (%)"
  )

# ggsave(here::here("ojs_growth_rate_by_year.png"))
```



<br/>

## Articles published

```{r}
total_records <-
  df %>%
  #drop_na(country) %>% 
  filter(active) %>% 
  select(record_count_2010:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  group_by(name) %>% 
  summarize(value = sum(value, na.rm = T)) %>% 
  summarize_all(sum) %>% 
  pull(value)
```

<br/>

Total articles published till date: __`r format(total_records, big.mark = ",", scientific = FALSE)`__


```{r, fig.retina=4, out.width="100%"}
df %>%
  drop_na(country) %>% 
  select(record_count_2010:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  group_by(name) %>% 
  summarize(value = sum(value, na.rm = T)) %>%
  ggplot(aes(name, value)) +
  #geom_point() +
  geom_col(fill = "#091f5e", alpha = 0.8) +
  scale_x_continuous(breaks = seq(2010, 2021, 1)) +
  scale_y_continuous(labels = scales::label_number_si()) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Year",
    y = "Articles per year",
    title = "Articles published per year in OJS journals",
    subtitle = "6.2 million articles published since 2010"
  )

# Savage(here::here("ojs_article_growth.png"))
```




## Average articles per journal

```{r}
df %>%
  filter(active) %>% 
  # drop_na(country) %>% 
  select(record_count_2010:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  filter(value > 0) %>%
  group_by(name) %>% 
  summarize(
    journals = n(),
    records = sum(value, na.rm = T)
  ) %>% 
  mutate(
    articles_per_journal = records/journals
  ) %>% 
  ggplot(aes(name, articles_per_journal)) +
  geom_col(alpha = 0.8) +
  geom_line() +
  geom_point() +
  hrbrthemes::theme_ipsum() +
  scale_y_continuous(limits = c(0, 50), breaks = seq(0, 50, 10)) +
  labs(
    x = "Year",
    y = "Articles per journal"
  )
```


# Countrywise

```{r, out.width="100%", fig.retina=4}
df %>%
  filter(country %in% c("Indonesia", "Brazil", "United States", "Spain", "India", "Colombia", "Ukraine", "Argentina", "Poland", "Mexico")) %>% 
  select(country, record_count_2010:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  filter(value >= 5) %>% 
  count(country, name) %>% 
  mutate(
    country = fct_reorder2(country, name, n)
  ) %>% 
  ggplot(aes(name, n, color = country)) +
  geom_line(size = 1) +
  facet_zoom(y = (country != "Indonesia" & country != "Brazil")) +
  #scale_x_continuous(breaks = seq(2010, 2020, 2)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(
    x = "Year",
    y = "Active Journals",
    color = "Country",
    title = "Growth in active journals for the top 10 countries"
  )
```



## Active journals (5 or more records published per year)

```{r, out.height="100%", out.width="100%", fig.height=30}
df %>%
  drop_na(country) %>%
  filter(country %in% c("Indonesia", "Brazil", "United States", "India", "Spain", "Colombia", "Argentina", "Ukraine", "Poland", "Mexico")) %>% 
  select(country, record_count_1980:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  filter(value >= 5) %>% 
  count(country, name) %>% 
  ggplot(aes(name, n)) +
  geom_line() +
  facet_wrap(vars(country), ncol = 1, scales = "free") +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Year",
    y = "Active journals"
  )
```

## Articles published

```{r, out.height="100%", out.width="100%", fig.height=30}
df %>%
  drop_na(country) %>% 
  filter(country %in% c("Indonesia", "Brazil", "United States", "India", "Spain", "Colombia", "Argentina", "Ukraine", "Poland", "Mexico")) %>% 
  select(country, record_count_1980:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  group_by(country, name) %>% 
  summarize(value = sum(value, na.rm = T)) %>%
  ungroup() %>% 
  ggplot(aes(name, value)) +
  geom_line() +
  facet_wrap(vars(country), ncol = 1, scales = "free") +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "Year",
    y = "Records"
  )
```


## Average articles per journal

```{r, out.height="100%", out.width="100%", fig.height=30}
df %>%
  drop_na(country) %>% 
  filter(country %in% c("Indonesia", "Brazil", "United States", "India", "Spain", "Colombia", "Argentina", "Ukraine", "Poland", "Mexico")) %>% 
  select(country, record_count_1980:record_count_2021) %>% 
  pivot_longer(cols = starts_with("record_count")) %>% 
  mutate(
    name = parse_number(name)
  ) %>% 
  filter(value > 0) %>%
  group_by(country, name) %>% 
  summarize(
    journals = n(),
    records = sum(value, na.rm = T)
  ) %>% 
  ungroup() %>% 
  mutate(
    articles_per_journal = records/journals
  ) %>% 
  ggplot(aes(name, articles_per_journal)) +
  geom_col(alpha=0.9) +
  facet_wrap(vars(country), ncol = 1, scales = "free") +
  hrbrthemes::theme_ipsum() +
  #scale_y_continuous(limits = c(0, 50)) +
  labs(
    x = "Year",
    y = "Articles per journal"
  )
```
