---
title: "For Cabells"
date: "Updated: `r format(Sys.Date(), format='%B %d %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 4
---

---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(tidyverse, countrycode, sf, state, htmltools, htmlwidgets, urltools, janitor, DT, RColorBrewer, plotly, readxl)
tld <- read_csv(here::here("data/tld-country.csv"))
tld_from_ip <- read_csv(here::here("data/tld_from_ip.csv"))
shapefile <- read_sf(here::here("data/TM_WORLD_BORDERS_SIMPL-0.3.shp"))
```

# Global

```{r}
# Data (Aug 5, 2021)
df <- read_csv(here::here("data/jonas/beacon-public.csv"))

canada.states <- 
  c("Alberta", "British Columbia", "Labrador", "Manitoba", "New Brunswick", "Newfoundland", "Nova Scotia", "Nunavut", "North West Terr.", "Ontario", "Prince Edward Is.", "Québec (Province)", "Saskatchewan", "Yukon")

# correcting some oai urls
df <- 
  df %>% 
  mutate(oai_url = if_else(str_detect(oai_url, "^//"), str_c("http:", oai_url), oai_url))


# getting domain and tld
df <-  
  bind_cols(
    df,
    df %>% pull(oai_url) %>% domain() %>% tld_extract()
  ) %>% 
  mutate(country_consolidated = str_to_lower(country_consolidated) %>% str_trim()) %>% 
  left_join(tld, by = c("country_consolidated" = "tld"))

# Cleaning countries + Mapping countries to continents
df <-
  df %>% 
  mutate(
    country = country_clean,
    ojs_v2 = str_detect(version, "^2"),
    ojs_v3 = str_detect(version, "^3"),
    version_clean = case_when(
      ojs_v2 ~ "Version 2",
      ojs_v3 ~ "Version 3",
      TRUE ~ "Other"
    )
  ) %>% 
  mutate(
    country = if_else(country == "Washington (State)", "United States", country),
    country = if_else(str_detect(country, "United States|New York|District of Columbia"), "United States", country),
    country = if_else(country %in% state.name, "United States", country),
    country = if_else(country %in% canada.states, "Canada", country),
    country = if_else(str_detect(country, "China"), "China", country),
    country = if_else(str_detect(country, "Armenia"), "Armenia", country),
    country = if_else(str_detect(country, "Georgia"), "Georgia", country),
    country = if_else(str_detect(country, "Australia|New South Wales|Queensland|Victoria"), "Australia", country),
    country = if_else(str_detect(country, "England|British"), "United Kingdom", country),
    country = if_else(str_detect(country, "Russia|Soviet Union"), "Russia", country),
    country = if_else(str_detect(country, "Palestine"), "Palestine", country),
    country = if_else(country == "Korea (South)", "South Korea", country)
  ) %>% 
  select(-country_clean)

continents <-
  df %>%
  pull(country) %>% 
  countrycode(origin = "country.name", destination = "continent")

df <- df %>% bind_cols(continents)

# rename last column to `continent`
names(df)[length(names(df))] <- "continent"

df <-
  df %>% 
  filter(total_record_count > 0) %>%
  filter(application == "ojs") %>%
  filter(record_count_2020 >= 5) %>%
  distinct(oai_url, repository_name, set_spec, .keep_all = T)
```


```{r, fig.retina=4}
# Create global map
df_world <-
  df %>%
  drop_na(country) %>%
  mutate(active = 1) %>% 
  group_by(country, continent) %>%
  summarize(
    total = sum(active, na.rm = T),
  ) %>%
  ungroup() %>%
  transmute(
    country,
    continent,
    total = replace_na(total, 0)
  )

shapefile %>% 
  clean_names() %>%
  rename(country = name) %>%
  left_join(
    read_csv(here::here("data/nations.csv")) %>% distinct(iso3, income), by = "iso3"
  ) %>% 
  mutate(
    country = if_else(country == "Libyan Arab Jamahiriya", "Libya", country),
    country = if_else(country == "United Republic of Tanzania", "Tanzania", country),
    country = if_else(country == "Cote d'Ivoire", "Côte d'Ivoire", country),
    country = if_else(country == "Congo", "Republic of the Congo", country),
    country = if_else(country == "Viet Nam", "Vietnam", country),
    country = if_else(str_detect(country, "Iran"), "Iran", country),
    country = if_else(str_detect(country, "Korea, Republic of"), "South Korea", country),
    country = if_else(str_detect(country, "Korea, Democratic People's Republic of"), "North Korea", country),
    country = if_else(str_detect(country, "Surinam"), "Surinam", country),
    income = if_else(income == "High income: OECD", "High income", income)
  ) %>%
  inner_join(df_world, by = "country") %>% 
  filter(country != "Antarctica") %>% 
  mutate(
    total = replace_na(total, 0),
    total = pmin(total, 500)
  ) %>%
  ggplot() +
  geom_sf(aes(fill = total), size = 0.3, show.legend = F) +
  scale_fill_gradientn(
    breaks = seq(0, 500, 250),
    colors = RColorBrewer::brewer.pal(n = 9, name = "Blues")
  ) +
  theme_void()

```



```{r, fig.retina=4}
# WoS data
df_wos <-
  read_table("/Users/saurabh/Downloads/wos_data_original.txt", na = c("NULL", "NA", "")) %>% 
  clean_names() %>% 
  remove_empty() %>% 
  filter(str_detect(issn, "^[0-9]{4}-[0-9]{3}[0-9xX]$")) %>% 
  distinct(issn) %>% 
  drop_na(issn)


df %>% 
  mutate(
    issn = str_extract(issn, "[^\n]+")
  ) %>%
  inner_join(df_wos, by = "issn") %>% 
  count(country) %>% 
  arrange(-n) %>% 
  head(10) %>% 
  mutate(country = fct_inorder(country) %>% fct_rev()) %>% 
  ggplot(aes(country, n)) +
  geom_col() +
  hrbrthemes::theme_ipsum() +
  coord_flip() +
  labs(
    x = "Country", y = "Number of journals"
  )

272/25671
```



```{r}
# Scopus data
df_scopus <-
  read_excel(here::here("data/scopus_nov2021.xlsx")) %>%
  clean_names() %>% 
  remove_empty() %>%
  select(issn = print_issn, e_issn, contains("cite_score"), everything()) %>%
  mutate(issn = if_else(is.na(issn), e_issn, issn)) %>%
  # mutate(issn = if_else(!is.na(e_issn), e_issn, issn)) %>%
  mutate_at(vars(contains("cite_score")), ~ as.numeric(.)) %>% 
  mutate(
    #issn = str_extract(issn, "[^\n]+"),
    issn = str_replace(issn, "-", "")
  ) %>%
  distinct(issn, .keep_all = T) %>% 
  drop_na(issn)


df %>% 
  drop_na(issn) %>%
  transmute(
    country,
    issn = str_extract(issn, "[^\n]+"),
    issn = str_replace(issn, "-", "")
  ) %>%
  inner_join(df_scopus, by = "issn") %>%
  drop_na(country) %>% 
  count(country) %>% 
  arrange(-n) %>% 
  head(10) %>% 
  mutate(country = fct_inorder(country) %>% fct_rev()) %>% 
  ggplot(aes(country, n)) +
  geom_col() +
  hrbrthemes::theme_ipsum() +
  coord_flip() +
  labs(
    x = "Country", y = "Number of journals"
  )


1307/25671


```



